volumes:
  app-node_modules:

services:

  ########################
  ## BEANSTALKD CONSOLE ##
  ########################

  lacuna-beanstalkd-console:
    container_name: 'lacuna-beanstalkd-console'
    depends_on:
      - 'lacuna-beanstalkd'
    image: 'schickling/beanstalkd-console'
    ports:
      - '2080:2080'

  ################
  ## BEANSTALKD ##
  ################

  lacuna-beanstalkd:
    container_name: 'lacuna-beanstalkd'
    image: 'schickling/beanstalkd'
    ports:
      - '11300:11300'

  ###############
  ## MEMCACHED ##
  ###############

  lacuna-memcached:
    container_name: 'lacuna-memcached'
    image: 'memcached'
    command: 
      # Persist cache in a file to save sessions (and other data) between restarts of the docker container
      - --memory-file /tempfs_mount/memory_file
    volumes:
      - ./memcached:/tempfs_mount

  ##################
  ## MYSQL SERVER ##
  ##################

  lacuna-mysql-server:
    container_name: 'lacuna-mysql-server'
    platform: linux/amd64
    environment:
      - 'MYSQL_ROOT_PASSWORD=lacuna'
    image: 'mysql:5.5'
    volumes:
      - './data:/var/lib/mysql'
    ports:
      - '3306:3306'

  ################
  ## PHPMYADMIN ##
  ################

  lacuna-phpmyadmin:
    container_name: 'lacuna-phpmyadmin'
    image: 'phpmyadmin:5.2-apache'
    environment:
      - 'PMA_HOST=lacuna-mysql-server'
    ports:
      - '8888:80'
    depends_on:
      - 'lacuna-mysql-server'
    links:
      - 'lacuna-mysql-server'

  ###########
  ## NGINX ##
  ###########

  lacuna-nginx:
    build:
      context: .
      dockerfile: ./docker/build-nginx/Dockerfile
    container_name: 'lacuna-nginx'
    depends_on:
      - 'lacuna-server'
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./etc-docker/nginx.conf:/etc/nginx/nginx.conf
      - ./etc-docker:/home/lacuna/server/etc
      - ./var:/home/lacuna/server/var
      - ./log/nginx:/etc/nginx/logs
      - ./captcha:/home/lacuna/server/captcha
      - ./assets:/home/lacuna/server/var/www/public/assets
      - ./var/www/public/api/api.css:/home/lacuna/server/var/www/public/api/api.css
      # TODO: fix CORS etc so that the app can run here properly
      # - ./app/dist/index.html:/home/lacuna/server/var/www/public/index.html
      # - ./app/dist/app:/home/lacuna/server/var/www/public/app
      - ./app/dist:/home/lacuna/server/var/www/public/app

  #########
  ## APP ##
  #########

  lacuna-app:
    build:
      context: .
      dockerfile: ./docker/build-app/Dockerfile 
    container_name: 'lacuna-app'
    command: npx vite build
    volumes:
      - app-node_modules:/usr/src/app/node_modules
      - ./app:/usr/src/app
    environment:
      - 'LACUNA_ASSETS_URL=https://lacuna.ocean74.net/assets/'
      - 'LACUNA_SERVER_URL=https://lacuna.ocean74.net'
      - 'LACUNA_API_KEY=anonymous'

  ############
  ## SERVER ##
  ############

  lacuna-server:
    build:
      context: .
      dockerfile: ./docker/build-server/Dockerfile
    command: '/bin/bash startdev.sh'
    container_name: 'lacuna-server'
    depends_on:
      - 'lacuna-mysql-server'
      - 'lacuna-phpmyadmin'
      - 'lacuna-memcached'
      - 'lacuna-beanstalkd'
    environment:
      - 'TLE_NO_MIDDLEWARE=1'
    ports:
      - '3050:5000'
    volumes:
      - ./bin:/home/lacuna/server/bin
      - ./captcha:/home/lacuna/server/captcha
      - ./docs:/home/lacuna/server/docs
      - ./etc-docker:/home/lacuna/server/etc
      - ./lib:/home/lacuna/server/lib
      - ./t:/home/lacuna/server/t
      - ./var:/home/lacuna/server/var
      - ./var/www/public/api/api.css:/home/lacuna/server/var/www/public/api/api.css
      - ./tmp:/tmp

  lacuna-server-building-scheduler:
    build:
      context: .
      dockerfile: ./docker/build-server/Dockerfile
    command: 'perl schedule_building.pl --noquiet --nodaemonize --initialize'
    container_name: 'lacuna-server-building-scheduler'
    depends_on:
      - 'lacuna-mysql-server'
      - 'lacuna-phpmyadmin'
      - 'lacuna-memcached'
      - 'lacuna-beanstalkd'
    volumes:
      - ./bin:/home/lacuna/server/bin
      - ./captcha:/home/lacuna/server/captcha
      - ./docs:/home/lacuna/server/docs
      - ./etc-docker:/home/lacuna/server/etc
      - ./lib:/home/lacuna/server/lib
      - ./t:/home/lacuna/server/t
      - ./var:/home/lacuna/server/var
      - ./var/www/public/api/api.css:/home/lacuna/server/var/www/public/api/api.css
      - ./tmp:/tmp

  lacuna-server-ship-scheduler:
    build:
      context: .
      dockerfile: ./docker/build-server/Dockerfile
    command: 'perl schedule_ship_arrival.pl --noquiet --nodaemonize --initialize'
    container_name: 'lacuna-server-ship-scheduler'
    depends_on:
      - 'lacuna-mysql-server'
      - 'lacuna-phpmyadmin'
      - 'lacuna-memcached'
      - 'lacuna-beanstalkd'
    volumes:
      - ./bin:/home/lacuna/server/bin
      - ./captcha:/home/lacuna/server/captcha
      - ./docs:/home/lacuna/server/docs
      - ./etc-docker:/home/lacuna/server/etc
      - ./lib:/home/lacuna/server/lib
      - ./t:/home/lacuna/server/t
      - ./var:/home/lacuna/server/var
      - ./var/www/public/api/api.css:/home/lacuna/server/var/www/public/api/api.css
      - ./tmp:/tmp

  lacuna-server-captcha-scheduler:
    build:
      context: .
      dockerfile: ./docker/build-server/Dockerfile
    command: 'perl schedule_captcha.pl --noquiet --nodaemonize'
    container_name: 'lacuna-server-captcha-scheduler'
    depends_on:
      - 'lacuna-mysql-server'
      - 'lacuna-phpmyadmin'
      - 'lacuna-memcached'
      - 'lacuna-beanstalkd'
    volumes:
      - ./bin:/home/lacuna/server/bin
      - ./captcha:/home/lacuna/server/captcha
      - ./docs:/home/lacuna/server/docs
      - ./etc-docker:/home/lacuna/server/etc
      - ./lib:/home/lacuna/server/lib
      - ./t:/home/lacuna/server/t
      - ./var:/home/lacuna/server/var
      - ./var/www/public/api/api.css:/home/lacuna/server/var/www/public/api/api.css
      - ./tmp:/tmp

  lacuna-server-script-scheduler:
    container_name: 'lacuna-server-script-scheduler'
    image: mcuadros/ofelia:latest
    depends_on:
      - lacuna-server
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc-docker/schedule.ini:/etc/ofelia.conf
